# SPI
#set_property PACKAGE_PIN T13 [get_ports {debug_spi\.CLK}]
set_property PACKAGE_PIN P10 [get_ports {debug_spi\.CLK}]
set_property PACKAGE_PIN R13 [get_ports {debug_spi\.CS}]
set_property PACKAGE_PIN T14 [get_ports {debug_spi\.MISO}]
set_property PACKAGE_PIN P14 [get_ports {debug_spi\.MOSI}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_spi\.CLK}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_spi\.CS}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_spi\.MISO}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_spi\.MOSI}]

# leds
set_property PACKAGE_PIN C16 [get_ports {leds[0][7]}]
set_property PACKAGE_PIN D15 [get_ports {leds[0][6]}]
set_property PACKAGE_PIN E15 [get_ports {leds[0][5]}]
set_property PACKAGE_PIN A14 [get_ports {leds[0][4]}]
set_property PACKAGE_PIN B15 [get_ports {leds[0][3]}]
set_property PACKAGE_PIN B16 [get_ports {leds[0][2]}]
set_property PACKAGE_PIN A15 [get_ports {leds[0][1]}]
set_property PACKAGE_PIN D16 [get_ports {leds[0][0]}]
set_property PACKAGE_PIN B11 [get_ports {leds[1][7]}]
set_property PACKAGE_PIN A12 [get_ports {leds[1][6]}]
set_property PACKAGE_PIN A13 [get_ports {leds[1][5]}]
set_property PACKAGE_PIN C8 [get_ports {leds[1][4]}]
set_property PACKAGE_PIN A9 [get_ports {leds[1][3]}]
set_property PACKAGE_PIN B10 [get_ports {leds[1][2]}]
set_property PACKAGE_PIN A10 [get_ports {leds[1][1]}]
set_property PACKAGE_PIN B12 [get_ports {leds[1][0]}]
set_property PACKAGE_PIN B6 [get_ports {leds[2][7]}]
set_property PACKAGE_PIN C7 [get_ports {leds[2][6]}]
set_property PACKAGE_PIN A8 [get_ports {leds[2][5]}]
set_property PACKAGE_PIN A3 [get_ports {leds[2][4]}]
set_property PACKAGE_PIN A4 [get_ports {leds[2][3]}]
set_property PACKAGE_PIN A5 [get_ports {leds[2][2]}]
set_property PACKAGE_PIN B5 [get_ports {leds[2][1]}]
set_property PACKAGE_PIN B7 [get_ports {leds[2][0]}]
set_property PACKAGE_PIN C1 [get_ports {leds[3][7]}]
set_property PACKAGE_PIN C2 [get_ports {leds[3][6]}]
set_property PACKAGE_PIN C3 [get_ports {leds[3][5]}]
set_property PACKAGE_PIN F2 [get_ports {leds[3][4]}]
set_property PACKAGE_PIN E1 [get_ports {leds[3][3]}]
set_property PACKAGE_PIN D3 [get_ports {leds[3][2]}]
set_property PACKAGE_PIN E2 [get_ports {leds[3][1]}]
set_property PACKAGE_PIN B1 [get_ports {leds[3][0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0][7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0][6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0][5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0][4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0][3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0][2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0][1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0][0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1][7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1][6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1][5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1][4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1][3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1][2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1][1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1][0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2][7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2][6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2][5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2][4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2][3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2][2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2][1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2][0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[3][7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[3][6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[3][5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[3][4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[3][3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[3][2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[3][1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[3][0]}]

#create_clock -period 1000.000 -name debug_spi_clock -waveform {0.000 500.000} [get_ports {debug_spi\\.CLK}]



#create_debug_core u_ila_0 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
#set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
#set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
#set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
#set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
#set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
#set_property port_width 1 [get_debug_ports u_ila_0/clk]
#connect_debug_port u_ila_0/clk [get_nets [list n_0_6_BUFG]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
#set_property port_width 16 [get_debug_ports u_ila_0/probe0]
#connect_debug_port u_ila_0/probe0 [get_nets [list {spi_data[0]} {spi_data[1]} {spi_data[2]} {spi_data[3]} {spi_data[4]} {spi_data[5]} {spi_data[6]} {spi_data[7]} {spi_data[8]} {spi_data[9]} {spi_data[10]} {spi_data[11]} {spi_data[12]} {spi_data[13]} {spi_data[14]} {spi_data[15]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
#set_property port_width 8 [get_debug_ports u_ila_0/probe1]
#connect_debug_port u_ila_0/probe1 [get_nets [list {command[0]} {command[1]} {command[2]} {command[3]} {command[4]} {command[5]} {command[6]} {command[7]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
#set_property port_width 8 [get_debug_ports u_ila_0/probe2]
#connect_debug_port u_ila_0/probe2 [get_nets [list {data[0]} {data[1]} {data[2]} {data[3]} {data[4]} {data[5]} {data[6]} {data[7]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
#set_property port_width 1 [get_debug_ports u_ila_0/probe3]
#connect_debug_port u_ila_0/probe3 [get_nets [list pending]]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets n_0_6_BUFG]

set_property IOSTANDARD LVCMOS33 [get_ports system_clock]
set_property PACKAGE_PIN F5 [get_ports system_clock]
#set_property PACKAGE_PIN N14 [get_ports system_clock]

#create_clock -period 30.518 -name system_clock -waveform {0.000 15.259} [get_ports system_clock]
create_clock -period 83.333 -name system_clock -waveform {0.000 41.667} [get_ports system_clock]

set_property PACKAGE_PIN D1 [get_ports {led_stripe[7]}]
set_property PACKAGE_PIN B4 [get_ports {led_stripe[6]}]
set_property PACKAGE_PIN A7 [get_ports {led_stripe[5]}]
set_property PACKAGE_PIN B9 [get_ports {led_stripe[4]}]
set_property PACKAGE_PIN B14 [get_ports {led_stripe[3]}]
set_property PACKAGE_PIN C14 [get_ports {led_stripe[2]}]
set_property PACKAGE_PIN E16 [get_ports {led_stripe[1]}]
set_property PACKAGE_PIN F15 [get_ports {led_stripe[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_stripe[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_stripe[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_stripe[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_stripe[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_stripe[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_stripe[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_stripe[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_stripe[0]}]



#create_debug_core u_ila_0 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
#set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
#set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
#set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
#set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
#set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
#set_property port_width 1 [get_debug_ports u_ila_0/clk]
#connect_debug_port u_ila_0/clk [get_nets [list system_clock_IBUF_BUFG]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
#set_property port_width 16 [get_debug_ports u_ila_0/probe0]
#connect_debug_port u_ila_0/probe0 [get_nets [list {spi_data[0]} {spi_data[1]} {spi_data[2]} {spi_data[3]} {spi_data[4]} {spi_data[5]} {spi_data[6]} {spi_data[7]} {spi_data[8]} {spi_data[9]} {spi_data[10]} {spi_data[11]} {spi_data[12]} {spi_data[13]} {spi_data[14]} {spi_data[15]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
#set_property port_width 16 [get_debug_ports u_ila_0/probe1]
#connect_debug_port u_ila_0/probe1 [get_nets [list {spi_current_data[0]} {spi_current_data[1]} {spi_current_data[2]} {spi_current_data[3]} {spi_current_data[4]} {spi_current_data[5]} {spi_current_data[6]} {spi_current_data[7]} {spi_current_data[8]} {spi_current_data[9]} {spi_current_data[10]} {spi_current_data[11]} {spi_current_data[12]} {spi_current_data[13]} {spi_current_data[14]} {spi_current_data[15]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
#set_property port_width 8 [get_debug_ports u_ila_0/probe2]
#connect_debug_port u_ila_0/probe2 [get_nets [list {spi_current_command[0]} {spi_current_command[1]} {spi_current_command[2]} {spi_current_command[3]} {spi_current_command[4]} {spi_current_command[5]} {spi_current_command[6]} {spi_current_command[7]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
#set_property port_width 16 [get_debug_ports u_ila_0/probe3]
#connect_debug_port u_ila_0/probe3 [get_nets [list {spi_current_addr[0]} {spi_current_addr[1]} {spi_current_addr[2]} {spi_current_addr[3]} {spi_current_addr[4]} {spi_current_addr[5]} {spi_current_addr[6]} {spi_current_addr[7]} {spi_current_addr[8]} {spi_current_addr[9]} {spi_current_addr[10]} {spi_current_addr[11]} {spi_current_addr[12]} {spi_current_addr[13]} {spi_current_addr[14]} {spi_current_addr[15]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
#set_property port_width 8 [get_debug_ports u_ila_0/probe4]
#connect_debug_port u_ila_0/probe4 [get_nets [list {bits_read[0]} {bits_read[1]} {bits_read[2]} {bits_read[3]} {bits_read[4]} {bits_read[5]} {bits_read[6]} {bits_read[7]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
#set_property port_width 16 [get_debug_ports u_ila_0/probe5]
#connect_debug_port u_ila_0/probe5 [get_nets [list {cdm16/instruction[0]} {cdm16/instruction[1]} {cdm16/instruction[2]} {cdm16/instruction[3]} {cdm16/instruction[4]} {cdm16/instruction[5]} {cdm16/instruction[6]} {cdm16/instruction[7]} {cdm16/instruction[8]} {cdm16/instruction[9]} {cdm16/instruction[10]} {cdm16/instruction[11]} {cdm16/instruction[12]} {cdm16/instruction[13]} {cdm16/instruction[14]} {cdm16/instruction[15]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
#set_property port_width 16 [get_debug_ports u_ila_0/probe6]
#connect_debug_port u_ila_0/probe6 [get_nets [list {cdm16/fetched_instruction[0]} {cdm16/fetched_instruction[1]} {cdm16/fetched_instruction[2]} {cdm16/fetched_instruction[3]} {cdm16/fetched_instruction[4]} {cdm16/fetched_instruction[5]} {cdm16/fetched_instruction[6]} {cdm16/fetched_instruction[7]} {cdm16/fetched_instruction[8]} {cdm16/fetched_instruction[9]} {cdm16/fetched_instruction[10]} {cdm16/fetched_instruction[11]} {cdm16/fetched_instruction[12]} {cdm16/fetched_instruction[13]} {cdm16/fetched_instruction[14]} {cdm16/fetched_instruction[15]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
#set_property port_width 1 [get_debug_ports u_ila_0/probe7]
#connect_debug_port u_ila_0/probe7 [get_nets [list dbg_clk]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
#set_property port_width 1 [get_debug_ports u_ila_0/probe8]
#connect_debug_port u_ila_0/probe8 [get_nets [list dbg_cw]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
#set_property port_width 1 [get_debug_ports u_ila_0/probe9]
#connect_debug_port u_ila_0/probe9 [get_nets [list dbg_miso]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
#set_property port_width 1 [get_debug_ports u_ila_0/probe10]
#connect_debug_port u_ila_0/probe10 [get_nets [list dbg_mosi]]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets system_clock_IBUF_BUFG]

set_property PACKAGE_PIN M16 [get_ports {buttons[0]}]
set_property PACKAGE_PIN M15 [get_ports {buttons[1]}]
set_property PACKAGE_PIN N16 [get_ports {buttons[2]}]
set_property PACKAGE_PIN P16 [get_ports {buttons[3]}]
set_property PACKAGE_PIN P15 [get_ports {buttons[4]}]
set_property PACKAGE_PIN R16 [get_ports {buttons[5]}]
set_property PACKAGE_PIN R15 [get_ports {buttons[6]}]
set_property PACKAGE_PIN T15 [get_ports {buttons[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[0]}]






set_property PACKAGE_PIN K1 [get_ports {dac\.CLK}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac\.CLK}]
set_property PACKAGE_PIN K2 [get_ports {dac\.CS}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac\.CS}]
set_property PACKAGE_PIN L2 [get_ports {dac\.MOSI}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac\.MOSI}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac\.MISO}]


set_property PACKAGE_PIN G1 [get_ports {adc\.CLK}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc\.CLK}]
set_property PACKAGE_PIN H2 [get_ports {adc\.CS}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc\.MOSI}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc\.MISO}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc\.CS}]
set_property PACKAGE_PIN H1 [get_ports {adc\.MISO}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list system_clock_IBUF_inst_n_0_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 11 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {audio_ctr[0]} {audio_ctr[1]} {audio_ctr[2]} {audio_ctr[3]} {audio_ctr[4]} {audio_ctr[5]} {audio_ctr[6]} {audio_ctr[7]} {audio_ctr[8]} {audio_ctr[9]} {audio_ctr[10]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 15 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {audio_mem_addr[0]} {audio_mem_addr[1]} {audio_mem_addr[2]} {audio_mem_addr[3]} {audio_mem_addr[4]} {audio_mem_addr[5]} {audio_mem_addr[6]} {audio_mem_addr[7]} {audio_mem_addr[8]} {audio_mem_addr[9]} {audio_mem_addr[10]} {audio_mem_addr[11]} {audio_mem_addr[12]} {audio_mem_addr[13]} {audio_mem_addr[14]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {audio_mem_in[0]} {audio_mem_in[1]} {audio_mem_in[2]} {audio_mem_in[3]} {audio_mem_in[4]} {audio_mem_in[5]} {audio_mem_in[6]} {audio_mem_in[7]} {audio_mem_in[8]} {audio_mem_in[9]} {audio_mem_in[10]} {audio_mem_in[11]} {audio_mem_in[12]} {audio_mem_in[13]} {audio_mem_in[14]} {audio_mem_in[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {audio_mem_out[0]} {audio_mem_out[1]} {audio_mem_out[2]} {audio_mem_out[3]} {audio_mem_out[4]} {audio_mem_out[5]} {audio_mem_out[6]} {audio_mem_out[7]} {audio_mem_out[8]} {audio_mem_out[9]} {audio_mem_out[10]} {audio_mem_out[11]} {audio_mem_out[12]} {audio_mem_out[13]} {audio_mem_out[14]} {audio_mem_out[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {audio_ptr[0]} {audio_ptr[1]} {audio_ptr[2]} {audio_ptr[3]} {audio_ptr[4]} {audio_ptr[5]} {audio_ptr[6]} {audio_ptr[7]} {audio_ptr[8]} {audio_ptr[9]} {audio_ptr[10]} {audio_ptr[11]} {audio_ptr[12]} {audio_ptr[13]} {audio_ptr[14]} {audio_ptr[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {dac_out[0]} {dac_out[1]} {dac_out[2]} {dac_out[3]} {dac_out[4]} {dac_out[5]} {dac_out[6]} {dac_out[7]} {dac_out[8]} {dac_out[9]} {dac_out[10]} {dac_out[11]} {dac_out[12]} {dac_out[13]} {dac_out[14]} {dac_out[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list audio_mem_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list debug_dac_cs]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list debug_dac_mosi]]
set_property PACKAGE_PIN T12 [get_ports {adc\.MOSI}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets system_clock_IBUF_inst_n_0_BUFG]
